products:
  Indomie:
    price: 3200
  Sabun:
    price: 4000
  Indomilk:
    price: 5250
  Keju:
    price: 16600
  Kecap:
    price: 4000
  Person:
    price: 10000
  Laptop:
    price: 10000
  Tv:
    price: 10000
  Cell Phone:
    price: 10000
